### ISSUE TITLE
Niedersachsen gives away their data for free too 😉

### ISSUE THREAD

**Issue by LilithWittmann** [MichaelKreil/opendata-hausumringe#1]
https://twitter.com/LGLN_Developers/status/1484629307716775936?s=20

**Comment by MichaelKreil** [comment]
Schwierig. Es fehlen ganz viele Daten, z.B. der Gebäudetyp.
Das kann ich so nicht als "offene Hausumringe" gelten lassen. :)

Aber dass man die Geometrien an dieser Stelle frei veröffentlicht, während man an anderer Stelle [24.000 €](https://www.lgln.niedersachsen.de/startseite/geodaten_karten/liegenschaftsinformationen_aus_alkis/hauskoordinaten_hausumringe/hauskoordinaten-und-hausumringe---angebot--kosten-50917.html) dafür verlangt, ist schon absurd!

**Comment by m0nac0** [comment]
@MichaelKreil Ich bin nur zufällig auf dieses Repository gestoßen und vielleicht irre ich mich, aber die Open Data 3D-Gebäudemodelle des LGLN enthalten laut Produktbeschreibung und in meinen Tests die "ALKIS-Gebäudefunktion", das scheint eine (recht genaue) Angabe des Gebäudetyps zu sein, oder?
