### ISSUE TITLE
Hessen: Einführung von Open Data zum 01.02.2022

### ISSUE THREAD

**Issue by tobwen** [MichaelKreil/opendata-hausumringe#2]
## tl;dr
Die Hessische Verwaltung für Bodenmanagement und Geoinformation stellt Ihnen ab dem 1. Februar 2022 Geodaten zur freien Nutzung über das Internet zur Verfügung.

## Quelle & Umfang
https://hvbg.hessen.de/open-data

## Nutzungsbestimmungen
Gemäß Quelle:
```
Jede Nutzung der Geobasisdaten, der zugehörigen Metadaten und der Daten der
Immobilienwertermittlung ist ohne Einschränkung oder Bedingung erlaubt.
```
Gemäß Realität: Einzelfallentscheidung, denn im Gesetzestext wird weiterhin stehen:
```
Wird bei der Nutzung der Geobasisdaten oder Metadaten ein Quellenvermerk
beigegeben, ist in diesem auf Veränderungen, Bearbeitungen, neue Gestaltungen
oder sonstige Abwandlungen der Geobasisdaten oder Metadaten hinzuweisen.
```
## Gesetzesgrundlage
http://starweb.hessen.de/cache/GVBL/2021/00036.pdf

**Comment by MichaelKreil** [comment]
Danke. Großartig!
Habe mir jetzt für dieses Issue einen Termin für den 1.2. eingetragen.

**Comment by tobwen** [comment]
![image](https://user-images.githubusercontent.com/1864057/150638308-5934b04d-7a27-4dc1-bbdc-af7bb6f595f1.png)
