### ISSUE TITLE
[feature request] Ergänzung der Preisliste

### ISSUE THREAD

**Issue by tobwen** [MichaelKreil/opendata-hausumringe#3]
Magst du noch darauf hinweisen, dass es sich hierbei (vermutlich) nur um den Preis für die interne Nutzung an einem Einzelplatz ggf. mit strengen Präsentationsrechten handelt?

Anders als bei _Open Data_ kann man diese Daten ja nicht einfach an Dritte weitergeben. Daher wäre der effektive Preis deutlich höher (AdV bzw. ZSHH hat ja einen entsprechenden Multiplikator).

**Comment by MichaelKreil** [comment]
Ich habe mal ein wenig das Wording verändert. Besser?
https://michaelkreil.github.io/opendata-hausumringe/

Die Gebührenverordnungen der Länder erschließen sich für mich nicht hundertprozentig. Soll ich einen Satz drunterschreiben? Was für einen?

**Comment by tobwen** [comment]
Sorry, habe deine Antwort vollkommen übersehen. Ich würde schreiben, dass es sich um den Mindestsatz für die interne Nutzung handelt und dass bei einer Veröffentlichung oder Weitergabe an Dritte inkl. Veredelung ein Multiplikator angewendet werden muss.

Nicht, dass die Nutzer jetzt denken, für 16.000 Euro bekommen sie die uneingeschränkten Nutzungsrechte an den Daten. Sie können die Daten weiterhin nur unternehmensintern und ggf. für Präsentationen nutzen...

**Comment by MichaelKreil** [comment]
Verstehe ich, aber können wir das in diesem Rahmen extrem kurz formulieren?
Kurz genug, dass es reinpasst, aber trotzdem inhaltlich korrekt?
Mein Vorschlag: "Gebühr min.: 24.000 €"

**Comment by tobwen** [comment]
Klar: _mind._ oder _ab_ und vermutlich _netto_.
